### ISSUE TITLE
Encountered an unexpected error

### ISSUE THREAD

**Issue by iamonuwa** [jpventura/sails-firebase#10]
Am getting this particular error (screenshot below) anytime I attempt to do this

I want to add a customer to an already existing business, I want many customers to one business.

What's the solution to this problem

Warm Regards

![image](https://user-images.githubusercontent.com/6551094/33232486-88f15a90-d207-11e7-9214-9e400c2bb735.png)

**Comment by jpventura** [comment]
@iamonuwa This adapter should not be used in production code because **many-to-one** and **many-to-many** relationships are not supported.

Latest Sails.js adapters rely on [driver-interface](https://github.com/node-machine/driver-interface), so if you require more complex features I recommend you use [sails-mongo](https://www.npmjs.com/package/sails-mongo).

**Comment by iamonuwa** [comment]
@jpventura thank you so much... I think I'll checkout [sails-mongo](https://www.npmjs.com/package/sails-mongo)

**Comment by jpventura** [comment]
May you attach the sails lift log? Seems like it is a server error.
